### ISSUE TITLE
npm start 运行报错

### ISSUE THREAD

**Issue by zentorwie** [chvin/react-tetris#2]
执行完npm install之后接着执行npm start会报错，输出如下：
```
-> % npm start

> react-tetris@1.0.0 start /Users/zentorwie/Codes/Frontend/react-tetris
> webpack-dev-server --progress

 70% 1/1 build modules http://0.0.0.0:8080/
webpack result is served from /
content is served from ./server
 32% 3/8 build modulesThe react/require-extension rule is deprecated. Please use the import/extensions rule from eslint-plugin-import instead.
Hash: 98044a932f7444f61380
Version: webpack 1.14.0
Time: 3764ms
     Asset     Size  Chunks             Chunk Names
    app.js   669 kB       0  [emitted]  main
 music.mp3  54.4 kB          [emitted]
loader.css   1.5 kB          [emitted]
chunk    {0} app.js (main) 226 kB [rendered]
    [0] multi main 52 bytes {0} [built] [1 error]
    [1] (webpack)-dev-server/client?http://0.0.0.0:8080 3.97 kB {0} [built]
    [2] ./~/url/url.js 23.3 kB {0} [built]
    [3] ./~/url/~/punycode/punycode.js 14.6 kB {0} [built]
    [4] (webpack)/buildin/module.js 251 bytes {0} [built]
    [5] ./~/url/util.js 314 bytes {0} [built]
    [6] ./~/querystring/index.js 127 bytes {0} [built]
    [7] ./~/querystring/decode.js 2.4 kB {0} [built]
    [8] ./~/querystring/encode.js 2.09 kB {0} [built]
    [9] ./~/strip-ansi/index.js 161 bytes {0} [built]
   [10] ./~/ansi-regex/index.js 135 bytes {0} [built]
   [11] (webpack)-dev-server/client/socket.js 856 bytes {0} [built]
   [12] ./~/sockjs-client/lib/entry.js 244 bytes {0} [built]
   [13] ./~/sockjs-client/lib/transport-list.js 613 bytes {0} [built]
   [14] ./~/sockjs-client/lib/transport/websocket.js 2.71 kB {0} [built]
   [15] ./~/node-libs-browser/~/process/browser.js 5.3 kB {0} [built]
   [16] ./~/sockjs-client/lib/utils/event.js 2 kB {0} [built]
   [17] ./~/sockjs-client/lib/utils/random.js 746 bytes {0} [built]
   [18] ./~/sockjs-client/lib/utils/browser-crypto.js 438 bytes {0} [built]
   [19] ./~/sockjs-client/lib/utils/url.js 975 bytes {0} [built]
   [20] ./~/url-parse/index.js 9.92 kB {0} [built]
   [21] ./~/requires-port/index.js 753 bytes {0} [built]
   [22] ./~/url-parse/lolcation.js 1.58 kB {0} [built]
   [23] ./~/querystringify/index.js 1.3 kB {0} [built]
   [24] ./~/debug/src/browser.js 4.68 kB {0} [built]
   [25] ./~/debug/src/debug.js 4.31 kB {0} [built]
   [26] ./~/ms/index.js 2.72 kB {0} [built]
   [27] ./~/inherits/inherits_browser.js 672 bytes {0} [built]
   [28] ./~/sockjs-client/lib/event/emitter.js 1.27 kB {0} [built]
   [29] ./~/sockjs-client/lib/event/eventtarget.js 1.85 kB {0} [built]
   [30] ./~/sockjs-client/lib/transport/browser/websocket.js 172 bytes {0} [built]
   [31] ./~/sockjs-client/lib/transport/xhr-streaming.js 1.25 kB {0} [built]
   [32] ./~/sockjs-client/lib/transport/lib/ajax-based.js 1.31 kB {0} [built]
   [33] ./~/sockjs-client/lib/transport/lib/sender-receiver.js 1.15 kB {0} [built]
   [34] ./~/sockjs-client/lib/transport/lib/buffered-sender.js 2.3 kB {0} [built]
   [35] ./~/sockjs-client/lib/transport/lib/polling.js 1.32 kB {0} [built]
   [36] ./~/sockjs-client/lib/transport/receiver/xhr.js 1.58 kB {0} [built]
   [37] ./~/sockjs-client/lib/transport/sender/xhr-cors.js 343 bytes {0} [built]
   [38] ./~/sockjs-client/lib/transport/browser/abstract-xhr.js 4.8 kB {0} [built]
   [39] ./~/sockjs-client/lib/transport/sender/xhr-local.js 352 bytes {0} [built]
   [40] ./~/sockjs-client/lib/utils/browser.js 560 bytes {0} [built]
   [41] ./~/sockjs-client/lib/transport/xdr-streaming.js 984 bytes {0} [built]
   [42] ./~/sockjs-client/lib/transport/sender/xdr.js 2.46 kB {0} [built]
   [43] ./~/sockjs-client/lib/transport/eventsource.js 766 bytes {0} [built]
   [44] ./~/sockjs-client/lib/transport/receiver/eventsource.js 1.58 kB {0} [built]
   [45] ./~/sockjs-client/lib/transport/browser/eventsource.js 37 bytes {0} [built]
   [46] ./~/sockjs-client/lib/transport/lib/iframe-wrap.js 981 bytes {0} [built]
   [47] ./~/sockjs-client/lib/transport/iframe.js 3.83 kB {0} [built]
   [48] ./~/json3/lib/json3.js 43.3 kB {0} [built]
   [49] (webpack)/buildin/amd-options.js 43 bytes {0} [built]
   [50] ./~/sockjs-client/lib/version.js 26 bytes {0} [built]
   [51] ./~/sockjs-client/lib/utils/iframe.js 5.06 kB {0} [built]
   [52] ./~/sockjs-client/lib/utils/object.js 532 bytes {0} [built]
   [53] ./~/sockjs-client/lib/transport/htmlfile.js 710 bytes {0} [built]
   [54] ./~/sockjs-client/lib/transport/receiver/htmlfile.js 2.2 kB {0} [built]
   [55] ./~/sockjs-client/lib/transport/xhr-polling.js 894 bytes {0} [built]
   [56] ./~/sockjs-client/lib/transport/xdr-polling.js 712 bytes {0} [built]
   [57] ./~/sockjs-client/lib/transport/jsonp-polling.js 1.02 kB {0} [built]
   [58] ./~/sockjs-client/lib/transport/receiver/jsonp.js 5.57 kB {0} [built]
   [59] ./~/sockjs-client/lib/transport/sender/jsonp.js 2.46 kB {0} [built]
   [60] ./~/sockjs-client/lib/main.js 11.9 kB {0} [built]
   [61] ./~/sockjs-client/lib/shims.js 18.2 kB {0} [built]
   [62] ./~/sockjs-client/lib/utils/escape.js 2.31 kB {0} [built]
   [63] ./~/sockjs-client/lib/utils/transport.js 1.35 kB {0} [built]
   [64] ./~/sockjs-client/lib/utils/log.js 450 bytes {0} [built]
   [65] ./~/sockjs-client/lib/event/event.js 477 bytes {0} [built]
   [66] ./~/sockjs-client/lib/location.js 177 bytes {0} [built]
   [67] ./~/sockjs-client/lib/event/close.js 295 bytes {0} [built]
   [68] ./~/sockjs-client/lib/event/trans-message.js 292 bytes {0} [built]
   [69] ./~/sockjs-client/lib/info-receiver.js 2.22 kB {0} [built]
   [70] ./~/sockjs-client/lib/transport/sender/xhr-fake.js 456 bytes {0} [built]
   [71] ./~/sockjs-client/lib/info-iframe.js 1.52 kB {0} [built]
   [72] ./~/sockjs-client/lib/info-iframe-receiver.js 791 bytes {0} [built]
   [73] ./~/sockjs-client/lib/info-ajax.js 1.03 kB {0} [built]
   [74] ./~/sockjs-client/lib/iframe-bootstrap.js 2.9 kB {0} [built]
   [75] ./~/sockjs-client/lib/facade.js 723 bytes {0} [built]
   [76] (webpack)/hot/dev-server.js 1.85 kB {0} [built]
   [77] (webpack)/hot/log-apply-result.js 813 bytes {0} [built]

ERROR in ./src/index.js
Module build failed: ReferenceError: [BABEL] /Users/zentorwie/Codes/Frontend/react-tetris/src/index.js: Unknown option: /Users/zentorwie/Codes/Frontend/react-tetris/node_modules/react/react.js.Children. Check out http://babeljs.io/docs/usage/options/ for more information about options.

A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:

Invalid:
  `{ presets: [{option: value}] }`
Valid:
  `{ presets: [['presetName', {option: value}]] }`

For more detailed information on preset configuration, please see http://babeljs.io/docs/plugins/#pluginpresets-options. (While processing preset: "/Users/zentorwie/Codes/Frontend/react-tetris/node_modules/react/react.js")
    at Logger.error (/Users/zentorwie/Codes/Frontend/react-tetris/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/zentorwie/Codes/Frontend/react-tetris/node_modules/babel-core/lib/transformation/file/options/option-manager.js:221:20)
    at /Users/zentorwie/Codes/Frontend/react-tetris/node_modules/babel-core/lib/transformation/file/options/option-manager.js:260:14
    at /Users/zentorwie/Codes/Frontend/react-tetris/node_modules/babel-core/lib/transformation/file/options/option-manager.js:329:22
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/zentorwie/Codes/Frontend/react-tetris/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/Users/zentorwie/Codes/Frontend/react-tetris/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/Users/zentorwie/Codes/Frontend/react-tetris/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/Users/zentorwie/Codes/Frontend/react-tetris/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/Users/zentorwie/Codes/Frontend/react-tetris/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/zentorwie/Codes/Frontend/react-tetris/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/zentorwie/Codes/Frontend/react-tetris/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/zentorwie/Codes/Frontend/react-tetris/node_modules/babel-loader/lib/index.js:38:20)
    at Object.module.exports (/Users/zentorwie/Codes/Frontend/react-tetris/node_modules/babel-loader/lib/index.js:133:12)
 @ multi main
webpack: bundle is now VALID.

```

环境信息：
```
OS: OS X 10.11
npm version的输出：
{ 'react-tetris': '1.0.0',
  npm: '3.10.9',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.9.2',
  openssl: '1.0.2j',
  uv: '1.9.1',
  v8: '5.1.281.88',
  zlib: '1.2.8' }
```

**Comment by zanjs** [comment]
Your config is

`presets: ['es2015', 'react']`

but the only preset you've installed is

`+-- babel-preset-es2015@6.18.0`

So your answer is

`npm install --save-dev babel-preset-react`

**Comment by chvin** [comment]
Thanks @zanjs ,In the `/Users/$nickname/node_modules`, I installed the babel-preset-react, so I found no problem
